name: weatherly_app
description: A customizable weather app with Firebase, weather API, and map support.

publish_to: 'none' # Remove this if you want to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6

  # Firebase
  firebase_core: ^2.27.0
  firebase_auth: ^4.17.5
  cloud_firestore: ^4.16.0
  firebase_messaging: ^14.7.15

  # Location and weather
  geolocator: ^10.1.0
  http: ^1.3.0  # ✅ Updated for flutter_map compatibility

  # Notifications
  flutter_local_notifications: ^16.3.2

  # State management and storage
  provider: ^6.1.2
  shared_preferences: ^2.2.2

  # Map support
  flutter_map: ^6.1.0   # ✅ Mapbox/Leaflet support
  latlong2: ^0.9.0      # ✅ For coordinates in flutter_map

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true

  assets:
    - assets/
